import os
import shutil

breakfast_box={
"logical_anomalies":
    [
        "The fruits and cereals/nuts in the meal box are incorrectly positioned.",
        "The fruits and cereals/nuts in the meal box are incorrectly positioned.",
        "The fruits and cereals/nuts in the meal box are incorrectly positioned.",
        "The meal box is missing almonds.",
        "The meal box is missing almonds.",
        "The meal box is missing almonds.",
        "The meal box is missing almonds.",
        "The meal box is missing almonds.",
        "The meal box is missing almonds.",
        "The meal box is missing almonds.",
        "The meal box is missing almonds.",
        "The meal box is missing almonds.",
        "The meal box is missing almonds.",
        "The meal box is missing almonds.",
        "The meal box is missing banana chips.",
        "The meal box is missing banana chips.",
        "The meal box is missing banana chips.",
        "The meal box is missing banana chips.",
        "The meal box is missing banana chips.",
        "The meal box is missing banana chips.",
        "The meal box is missing banana chips.",
        "The meal box is missing banana chips.",
        "The meal box is missing banana chips.",
        "The meal box is missing banana chips.",
        "The meal box is missing banana chips.",
        "The meal box is missing cereals.",
        "The meal box is missing cereals.",
        "The meal box is missing cereals.",
        "The meal box is missing cereals.",
        "The meal box is missing cereals.",
        "The meal box is missing cereals.",
        "The meal box is missing cereals.",
        "The meal box is missing cereals.",
        "The meal box is missing cereals, almonds, and banana chips.",
        "The meal box is missing cereals, almonds, and banana chips.",
        "The meal box is missing cereals, almonds, and banana chips.",
        "The meal box is missing cereals, almonds, and banana chips.",
        "The meal box is missing almonds and banana chips.",
        "The meal box is missing almonds and banana chips.",
        "The meal box is missing almonds and banana chips.",
        "The meal box is missing almonds and banana chips.",
        "The meal box is missing almonds and banana chips.",
        "The meal box is missing almonds and banana chips.",
        "The meal box is missing almonds and banana chips.",
        "The cereals and nuts spilled over to the other side of the meal box.",
        "The cereals and nuts spilled over to the other side of the meal box.",
        "The cereals and nuts spilled over to the other side of the meal box.",
        "The cereals and nuts spilled over to the other side of the meal box.",
        "The cereals and nuts are insufficient in the meal box.",
        "The cereals and nuts are insufficient in the meal box.",
        "The cereals and nuts are insufficient in the meal box.",
        "The cereals and nuts are insufficient in the meal box.",
        "Incorrect fruit ratio, 3 nectarines and 0 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio, 3 nectarines and 0 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio, 2 nectarines and 1 tangerine, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio, 0 nectarines and 3 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio, 2 nectarines and 1 tangerine, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio, 2 nectarines and 1 tangerine, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio and missing fruits, 0 nectarines and 1 tangerine, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio and missing nectarines, 0 nectarines and 2 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio and missing nectarines, 0 nectarines and 2 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio and missing fruits, 0 nectarines and 1 tangerine, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio and missing tangerines, 1 nectarine and 1 tangerine, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio, 3 nectarines and 0 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio, 0 nectarines and 3 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Missing fruits, 0 nectarines and 0 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio, 0 nectarines and 3 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Missing fruits, 0 nectarines and 0 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio, 0 nectarines and 4 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio and missing tangerines, 1 nectarine and 1 tangerine, instead of the correct 2 tangerines and 1 nectarine.",
        "Incorrect fruit ratio, 0 nectarines and 4 tangerines, instead of the correct 2 tangerines and 1 nectarine.",
        "The meal box contains an excess of almonds and banana chips, with insufficient cereal.",
        "The meal box contains excess cereals, with almonds and banana chips missing.",
        "The meal box contains excess cereals, with insufficient almonds and banana chips.",
        "The meal box contains an excess of almonds and banana chips, with insufficient cereal.",
        "The meal box contains excess cereals, with almonds and banana chips missing.",
        "The meal box contains excess cereals, with insufficient almonds and banana chips.",
        "The meal box contains excess cereals, with insufficient almonds and banana chips.",
        "The meal box contains an excess of almonds and banana chips, with cereal missing.",
        "The meal box contains an excess of almonds and banana chips, with cereal missing.",
        "The meal box contains an excess of almonds and banana chips, with insufficient cereal.",
        "The meal box contains excess cereals, with almonds and banana chips missing.",
        "The meal box contains an excess of almonds and banana chips, with cereal missing."
    ],
    "structural_anomalies":
    [
        "The meal box is damaged.",
        "The meal box is damaged.",
        "The meal box is damaged.",
        "The meal box is damaged.",
        "The meal box mixed in cookies.",
        "The meal box mixed in a nail.",
        "The meal box mixed in water.",
        "The meal box mixed in a ping pong ball.",
        "The meal box mixed in orange peel.",
        "The meal box mixed in a nail.",
        "The meal box mixed in orange peel.",
        "The meal box mixed in a box fragment.",
        "The meal box mixed in foreign matter.",
        "The meal box mixed in tape.",
        "The meal box mixed in a keychain.",
        "The meal box mixed in water.",
        "The meal box mixed in a ping pong ball.",
        "The meal box mixed in orange peel.",
        "The meal box mixed in toilet paper.",
        "The meal box mixed in a pill.",
        "The meal box mixed in label strips.",
        "The meal box mixed in a nail.",
        "The meal box mixed in liquid.",
        "The meal box mixed in thin sticks.",
        "The meal box mixed in an apple.",
        "The meal box mixed in a pill.",
        "The meal box mixed in cookies.",
        "The meal box mixed in a foil wrapper.",
        "The meal box mixed in dried fruits.",
        "The meal box mixed in dried fruits.",
        "The meal box mixed in liquid.",
        "The meal box mixed in a pill.",
        "The meal box mixed in dried fruits.",
        "The meal box mixed in a pill.",
        "The meal box mixed in a pill.",
        "The meal box mixed in label strips.",
        "The meal box mixed in tape.",
        "The meal box mixed in dried fruits.",
        "The meal box mixed in yellow cereal flakes.",
        "The meal box mixed in a box fragment.",
        "The meal box mixed in white beans.",
        "The meal box mixed in yellow cereal flakes.",
        "The meal box mixed in white thread.",
        "The meal box mixed in a pill.",
        "A tangerine damaged.",
        "A tangerine damaged.",
        "A tangerine damaged.",
        "A nectarine damaged.",
        "A tangerine damaged.",
        "A nectarine damaged.",
        "A nectarine damaged.",
        "A nectarine damaged.",
        "A tangerine damaged.",
        "A tangerine damaged.",
        "A nectarine damaged.",
        "A nectarine damaged.",
        "A tangerine damaged.",
        "A tangerine damaged.",
        "A tangerine damaged.",
        "A nectarine damaged.",
        "A nectarine damaged.",
        "A tangerine damaged.",
        "A tangerine damaged.",
        "A nectarine damaged.",
        "A tangerine damaged.",
        "A tangerine damaged.",
        "A nectarine damaged.",
        "A tangerine damaged.",
        "A tangerine damaged.",
        "A nectarine damaged.",
        "A tangerine damaged.",
        "A nectarine damaged.",
        "A tangerine damaged.",
        "A nectarine damaged.",
        "A nectarine damaged.",
        "The cereals, almonds, and banana chips are mixed together.",
        "The cereals, almonds, and banana chips are mixed together.",
        "The cereals, almonds, and banana chips are mixed together.",
        "The cereals, almonds, and banana chips are mixed together.",
        "The cereals, almonds, and banana chips are mixed together.",
        "The cereals, almonds, and banana chips are mixed together.",
        "The cereals, almonds, and banana chips are mixed together.",
        "The cereals, almonds, and banana chips are mixed together.",
        "The crushed almonds and banana chips are mixed together.",
        "The crushed almonds and banana chips are mixed together.",
        "The crushed almonds and banana chips are mixed together.",
        "The crushed almonds and banana chips are mixed together.",
        "The crushed almonds and banana chips are mixed together.",
        "The crushed almonds and banana chips are mixed together.",
        "The crushed almonds and banana chips are mixed together."
    ]
}

juice_bottle={
    "logical_anomalies":
    [
        "Orange juice bottle with missing top and bottom labels.",
        "Cherry juice bottle with missing top and bottom labels.",
        "Banana juice bottle with missing top and bottom labels.",
        "Orange juice bottle with missing top and bottom labels.",
        "Cherry juice bottle with missing top and bottom labels.",
        "Banana juice bottle with missing top and bottom labels.",
        "Cherry juice bottle with missing top and bottom labels.",
        "Banana juice bottle with missing top and bottom labels.",
        "Banana juice bottle with missing top and bottom labels.",
        "Cherry juice bottle with missing top and bottom labels.",
        "Orange juice bottle with missing top and bottom labels.",
        "Orange juice bottle with missing top and bottom labels.",
        "Cherry juice bottle with missing bottom label.",
        "Cherry juice bottle with missing bottom label.",
        "Banana juice bottle with missing bottom label.",
        "Cherry juice bottle with missing bottom label.",
        "Orange juice bottle with missing bottom label.",
        "Orange juice bottle with missing bottom label.",
        "Orange juice bottle with missing bottom label.",
        "Banana juice bottle with missing bottom label.",
        "Banana juice bottle with missing bottom label.",
        "Cherry juice bottle with missing bottom label.",
        "Orange juice bottle with missing bottom label.",
        "Banana juice bottle with missing bottom label.",
        "Empty bottle with no banana juice.",
        "Empty bottle with no orange juice.",
        "Empty bottle with no orange juice.",
        "Empty bottle with no banana juice.",
        "Empty bottle with no orange juice.",
        "Empty bottle with no banana juice.",
        "Empty bottle with no cherry juice.",
        "Empty bottle with no orange juice.",
        "Empty bottle with no cherry juice.",
        "Empty bottle with no banana juice.",
        "Empty bottle with no cherry juice.",
        "Empty bottle with no cherry juice.",
        "Orange juice label with misplaced fruit icon.",
        "Orange juice label with misplaced fruit icon.",
        "Cherry juice label with misplaced fruit icon.",
        "Banana juice label with misplaced fruit icon.",
        "Cherry juice label with misplaced fruit icon.",
        "Orange juice label with misplaced fruit icon.",
        "Orange juice label with misplaced fruit icon.",
        "Cherry juice label with misplaced fruit icon.",
        "Banana juice label with misplaced fruit icon.",
        "Cherry juice label with misplaced fruit icon.",
        "Orange juice label missing fruit icon.",
        "Banana juice label missing fruit icon.",
        "Orange juice label missing fruit icon.",
        "Banana juice label missing fruit icon.",
        "Orange juice label missing fruit icon.",
        "Misplaced top label on banana juice container.",
        "Misplaced bottom label on cherry juice container.",
        "Misplaced top label on cherry juice container.",
        "Misplaced bottom label on orange juice container.",
        "Misplaced top label on banana juice container.",
        "Misplaced top label on cherry juice container.",
        "Misplaced top label on banana juice container.",
        "Misplaced bottom label on orange juice container.",
        "Misplaced bottom label on cherry juice container.",
        "Top and bottom labels swapped on cherry juice bottle.",
        "Top and bottom labels swapped on cherry juice bottle.",
        "Top and bottom labels swapped on orange juice bottle.",
        "Top and bottom labels swapped on cherry juice bottle.",
        "Top and bottom labels swapped on banana juice bottle.",
        "Top and bottom labels swapped on orange juice bottle.",
        "Top and bottom labels swapped on cherry juice bottle.",
        "Top and bottom labels swapped on banana juice bottle.",
        "Top and bottom labels swapped on orange juice bottle.",
        "Top and bottom labels swapped on banana juice bottle.",
        "Top and bottom labels swapped on orange juice bottle.",
        "Top and bottom labels swapped on banana juice bottle.",
        "Orange juice bottle missing top label.",
        "Banana juice bottle missing top label.",
        "Cherry juice bottle missing top label.",
        "Cherry juice bottle missing top label.",
        "Cherry juice bottle missing top label.",
        "Orange juice bottle missing top label.",
        "Orange juice bottle missing top label.",
        "Orange juice bottle missing top label.",
        "Cherry juice bottle missing top label.",
        "Banana juice bottle missing top label.",
        "Banana juice bottle missing top label.",
        "Banana juice bottle missing top label.",
        "Orange juice bottle with insufficient fill level.",
        "Cherry juice bottle with excessive fill level.",
        "Cherry juice bottle with insufficient fill level.",
        "Cherry juice bottle with excessive fill level.",
        "Banana juice bottle with insufficient fill level.",
        "Orange juice bottle with insufficient fill level.",
        "Cherry juice bottle with insufficient fill level.",
        "Cherry juice bottle with excessive fill level.",
        "Cherry juice bottle with insufficient fill level.",
        "Orange juice bottle with insufficient fill level.",
        "Orange juice bottle with insufficient fill level.",
        "Cherry juice bottle with insufficient fill level.",
        "Orange juice bottle with insufficient fill level.",
        "Banana juice bottle with insufficient fill level.",
        "Cherry juice bottle with excessive fill level.",
        "Orange juice bottle with insufficient fill level.",
        "Banana juice bottle with insufficient fill level.",
        "Banana juice bottle with insufficient fill level.",
        "Banana juice bottle with excessive fill level.",
        "Banana juice bottle with excessive fill level.",
        "Banana juice bottle with insufficient fill level.",
        "Cherry juice bottle with insufficient fill level.",
        "Cherry juice bottle with insufficient fill level.",
        "Banana juice bottle with excessive fill level.",
        "Orange juice bottle with insufficient fill level.",
        "Orange juice bottle with excessive fill level.",
        "Banana juice bottle with insufficient fill level.",
        "Orange juice bottle with insufficient fill level.",
        "Banana juice bottle with excessive fill level.",
        "Banana juice bottle with insufficient fill level.",
        "Banana juice bottle with insufficient fill level.",
        "Orange juice bottle with excessive fill level.",
        "Cherry juice bottle with insufficient fill level.",
        "Orange juice bottle with insufficient fill level.",
        "Orange juice bottle with excessive fill level.",
        "Orange juice bottle with excessive fill level.",
        "Cherry juice mislabeled as banana juice.",
        "Banana juice mislabeled as cherry juice.",
        "Cherry juice mislabeled as orange juice.",
        "Orange juice mislabeled as cherry juice.",
        "Orange juice mislabeled as banana juice.",
        "Cherry juice mislabeled as banana juice.",
        "Orange juice mislabeled as banana juice.",
        "Banana juice mislabeled as orange juice.",
        "Banana juice mislabeled as cherry juice.",
        "Orange juice mislabeled as cherry juice.",
        "Banana juice mislabeled as orange juice.",
        "Banana juice mislabeled as orange juice.",
        "Orange juice mislabeled as banana juice.",
        "Cherry juice mislabeled as banana juice.",
        "Orange juice mislabeled as banana juice.",
        "Banana juice mislabeled as orange juice.",
        "Cherry juice mislabeled as banana juice.",
        "Banana juice mislabeled as cherry juice.",
        "Orange juice mislabeled as cherry juice.",
        "Cherry juice mislabeled as orange juice.",
        "Banana juice mislabeled as cherry juice.",
        "Orange juice mislabeled as cherry juice."
    ],
    "structural_anomalies":
    [
        "Orange juice is contaminated with liquid orange objects.",
        "Cherry juice has an anomalous lid.",
        "The label on the orange juice is contaminated.",
        "Orange juice is contaminated with yellow strip-shaped objects.",
        "Cherry juice is contaminated with white objects.",
        "Cherry juice is contaminated with red strip-shaped objects.",
        "Cherry juice is contaminated with white strip-shaped objects.",
        "Orange juice is contaminated with liquid orange objects.",
        "Orange juice is contaminated with yellow strip-shaped objects.",
        "The banana juice bottle shows red color contamination.",
        "Cherry juice is contaminated with anomalous objects.",
        "Banana juice is contaminated with orange objects.",
        "Banana juice is contaminated with orange objects.",
        "Banana juice is contaminated with green objects.",
        "Banana juice is contaminated with orange objects.",
        "Cherry juice is contaminated with white strip-shaped objects.",
        "Cherry juice is contaminated with orange strip-shaped objects.",
        "Cherry juice is contaminated with red strip-shaped objects.",
        "Orange juice is contaminated with white objects.",
        "Banana juice is contaminated with green objects.",
        "Orange juice is contaminated with white strip-shaped objects.",
        "Cherry juice is contaminated with white objects.",
        "The label on the banana juice shows red color contamination.",
        "Cherry juice is contaminated with white strip-shaped objects.",
        "Banana juice is contaminated with orange objects.",
        "Cherry juice is contaminated with orange strip-shaped objects.",
        "Orange juice is contaminated with white objects.",
        "The orange juice label has an incomplete orange icon.",
        "The orange juice label has an incomplete orange icon.",
        "The orange juice label has an incomplete orange icon.",
        "The orange juice label has an incomplete orange icon.",
        "The cherry juice label has an incomplete cherry icon.",
        "The cherry juice label has an incomplete cherry icon.",
        "The orange juice label has an incomplete orange icon.",
        "The cherry juice label has an incomplete cherry icon.",
        "The cherry juice label has an incomplete cherry icon.",
        "The cherry juice label has an incomplete cherry icon.",
        "The cherry juice label has an incomplete cherry icon.",
        "The orange juice label displays an unknown fruit icon.",
        "The banana juice label displays an unknown fruit icon.",
        "The orange juice label displays an unknown fruit icon.",
        "The cherry juice label displays an unknown fruit icon.",
        "The banana juice label displays an unknown fruit icon.",
        "The cherry juice label displays an unknown fruit icon.",
        "Banana juice is contaminated with abnormal liquids.",
        "Banana juice is contaminated with abnormal liquids.",
        "Banana juice is contaminated with abnormal liquids.",
        "Orange juice is contaminated with abnormal liquids.",
        "Banana juice is contaminated with abnormal liquids.",
        "Orange juice is contaminated with abnormal liquids.",
        "Banana juice is contaminated with abnormal liquids.",
        "Banana juice is contaminated with abnormal liquids.",
        "Orange juice is contaminated with abnormal liquids.",
        "Banana juice is contaminated with abnormal liquids.",
        "Banana juice is contaminated with abnormal liquids.",
        "Banana juice is contaminated with abnormal liquids.",
        "Orange juice is contaminated with abnormal liquids.",
        "Banana juice is contaminated with abnormal liquids.",
        "The label text is incomplete with the percentage sign missing.",
        "The label text is incomplete with the number missing.",
        "The label text is incomplete with the number missing.",
        "The label text is incomplete with the number missing.",
        "The label text is incomplete with the number missing.",
        "The label text is incomplete with the number missing.",
        "The top label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The bottom label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The bottom label of the bottle is damaged.",
        "The bottom label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The bottom label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The bottom label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The bottom label of the bottle is damaged.",
        "The bottom label of the bottle is damaged.",
        "The top label of the bottle is damaged.",
        "The banana juice label is rotated.",
        "The cherry juice label is rotated.",
        "The orange juice label is rotated.",
        "The banana juice label is rotated.",
        "The orange juice label is rotated.",
        "The cherry juice label is rotated.",
        "The cherry juice label is rotated.",
        "The banana juice label is rotated.",
        "The orange juice label is rotated."
    ]
}

pushpins={
"logical_anomalies":
    [
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "One compartment of the plastic case has one additional pushpin.",
        "Two compartments of the plastic case each have one additional pushpin.",
        "Two compartments of the plastic case each have one additional pushpin.",
        "Two compartments of the plastic case each have one additional pushpin.",
        "Two compartments of the plastic case each have one additional pushpin.",
        "Two compartments of the plastic case each have one additional pushpin.",
        "Two compartments of the plastic case each have one additional pushpin.",
        "Each compartment of the plastic case have one additional pushpin.",
        "Each compartment of the plastic case have one additional pushpin.",
        "Each compartment of the plastic case have one additional pushpin.",
        "Each compartment of the plastic case have one additional pushpin.",
        "Each compartment of the plastic case have one additional pushpin.",
        "Each compartment of the plastic case have one additional pushpin.",
        "Each compartment of the plastic case have one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin, while another has one additional pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "One compartment of the plastic case is missing one pushpin.",
        "Two compartments of the plastic case are each missing one pushpin.",
        "Two compartments of the plastic case are each missing one pushpin.",
        "Two compartments of the plastic case are each missing one pushpin.",
        "Two compartments of the plastic case are each missing one pushpin.",
        "Two compartments of the plastic case are each missing one pushpin.",
        "Two compartments of the plastic case are each missing one pushpin.",
        "All compartments of the plastic case are missing one pushpin.",
        "All compartments of the plastic case are missing one pushpin.",
        "All compartments of the plastic case are missing one pushpin.",
        "All compartments of the plastic case are missing one pushpin.",
        "All compartments of the plastic case are missing one pushpin.",
        "Plastic case is missing one separator.",
        "Plastic case is missing one separator.",
        "Plastic case is missing one separator.",
        "Plastic case is missing one separator.",
        "Plastic case is missing one separator.",
        "Plastic case is missing one separator.",
        "Plastic case is missing one separator.",
        "Plastic case is missing one separator.",
        "One compartment of the plastic case has two additional pushpins.",
        "One compartment of the plastic case has two additional pushpins.",
        "One compartment of the plastic case has two additional pushpins.",
        "One compartment of the plastic case has two additional pushpins.",
        "One compartment of the plastic case has two additional pushpins.",
        "One compartment of the plastic case has two additional pushpins.",
        "Plastic case is missing two separators.",
        "Plastic case is missing two separators.",
        "Plastic case is missing two separators.",
        "Plastic case is missing two separators.",
        "Plastic case is missing two separators.",
        "Three compartments of the plastic case are each missing one pushpin.",
        "Three compartments of the plastic case are each missing one pushpin.",
        "Three compartments of the plastic case are each missing one pushpin.",
        "Three compartments of the plastic case are each missing one pushpin.",
        "Three compartments of the plastic case are each missing one pushpin.",
        "Three compartments of the plastic case are each missing one pushpin.",
        "Three compartments of the plastic case are each missing one pushpin.",
        "Three compartments of the plastic case are each missing one pushpin.",
        "Three compartments of the plastic case are each missing one pushpin.",
        "Three compartments of the plastic case are each missing one pushpin."
    ],
    "structural_anomalies":
    [
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with a fractured front end.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with a fractured front end.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with a fractured front end.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with a fractured front end.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with a fractured front end.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with a fractured front end.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with a fractured front end.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with a fractured front end.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with a fractured front end.",
        "One compartment of the plastic case has a pushpin with a fractured front end.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with obvious breakage.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has a pushpin with color contamination.",
        "One compartment of the plastic case has an extrone pushpin with green color.",
        "One compartment of the plastic case has an unexpected yellow pushpin-like object.",
        "One compartment of the plastic case has an unexpected yellow pushpin-like object.",
        "One compartment of the plastic case has an unexpected yellow pushpin-like object.",
        "One compartment of the plastic case has an unexpected yellow pushpin-like object.",
        "One compartment of the plastic case has an anomaly object mixed in with pushpins.",
        "One compartment of the plastic case has an additional white pushpin.",
        "One compartment of the plastic case has an additional red pushpin.",
        "One compartment of the plastic case has an unexpected yellow pushpin-like object.",
        "One compartment of the plastic case has an additional white pushpin.",
        "One compartment of the plastic case has an unexpected yellow pushpin-like object.",
        "One compartment of the plastic case has a nail mixed in.",
        "One compartment of the plastic case has an unexpected yellow pushpin-like object.",
        "One compartment of the plastic case has a nail mixed in.",
        "One compartment of the plastic case has an anomaly object mixed in with pushpins.",
        "One compartment of the plastic case has an additional blue pushpin.",
        "One compartment of the plastic case has an additional red pushpin.",
        "One compartment of the plastic case has an extrone pushpin with green color.",
        "One compartment of the plastic case has an additional blue pushpin.",
        "One compartment of the plastic case has an unexpected yellow pushpin-like object.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end.",
        "One compartment of the plastic case has a pushpin with a bent front end."
    ]
}

screw_bag={
"logical_anomalies":
    [
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw exceeding standard length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains a screw with insufficient length.",
        "The screw bag contains an additional nut.",
        "The screw bag includes an extra long screw.",
        "The screw bag detected an extra washer.",
        "The screw bag detected an extra washer.",
        "The screw bag contains an additional nut.",
        "The screw bag includes an extra long screw.",
        "The screw bag contains an additional nut.",
        "The screw bag detected an extra washer.",
        "The screw bag includes an extra short screw.",
        "The screw bag includes an extra short screw.",
        "The screw bag contains an additional nut.",
        "The screw bag includes an extra long screw.",
        "The screw bag detected an extra washer.",
        "The screw bag detected an extra washer.",
        "The screw bag detected an extra washer.",
        "The screw bag includes an extra short screw.",
        "The screw bag contains an additional nut.",
        "The screw bag includes an extra long screw.",
        "The screw bag includes an extra long screw.",
        "The screw bag includes an extra short screw.",
        "The screw bag contains an additional nut.",
        "The screw bag includes an extra long screw.",
        "The screw bag includes an extra short screw.",
        "The screw bag includes an extra short screw.",
        "The screw set is missing a long screw.",
        "The screw set is missing a washer.",
        "The screw set is missing a short screw.",
        "The screw set is missing a nut.",
        "The screw set is missing a nut.",
        "The screw set is missing a long screw.",
        "The screw set is missing a washer.",
        "The screw set is missing a washer.",
        "The screw set is missing a short screw.",
        "The screw set is missing a long screw.",
        "The screw set is missing a short screw.",
        "The screw set is missing a long screw.",
        "The screw set is missing a washer.",
        "The screw set is missing a nut.",
        "The screw set is missing a short screw.",
        "The screw set is missing a nut.",
        "The screw set is missing a long screw.",
        "The screw set is missing a short screw.",
        "The screw set is missing a washer.",
        "The screw set is missing a washer.",
        "The screw set is missing a long screw.",
        "The screw set is missing a nut.",
        "The screw set is missing a nut.",
        "The screw set is missing a short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a pair of very short screws.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a pair of very short screws.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a pair of very short screws.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a pair of very short screws.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a pair of very short screws.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a single very short screw.",
        "The screw bag includes a pair of very short screws.",
        "The screw bag includes a pair of very short screws.",
        "The screw bag contains two extra nuts, but two washers are not included.",
        "The screw bag contains two extra nuts, but two washers are not included.",
        "The screw bag contains an additional nut, but a washer is missing.",
        "The screw bag contains two additional washers, but two nuts are not included.",
        "The screw bag detected an extra washer, but a nut is missing.",
        "The screw bag detected an extra washer, but a nut is missing.",
        "The screw bag contains an additional nut, but a washer is missing.",
        "The screw bag contains an additional nut, but a washer is missing.",
        "The screw bag contains two extra nuts, but two washers are not included.",
        "The screw bag detected an extra washer, but a nut is missing.",
        "The screw bag detected an extra washer, but a nut is missing.",
        "The screw bag contains two additional washers, but two nuts are not included.",
        "The screw bag detected an extra washer, but a nut is missing.",
        "The screw bag contains two additional washers, but two nuts are not included.",
        "The screw bag contains two extra nuts, but two washers are not included.",
        "The screw bag contains two additional washers, but two nuts are not included.",
        "The screw bag contains two extra nuts, but two washers are not included.",
        "The screw bag contains an additional nut, but a washer is missing.",
        "The screw bag contains an additional nut, but a washer is missing.",
        "The screw bag contains two additional washers, but two nuts are not included.",
        "The screw bag contains two additional washers, but two nuts are not included.",
        "The screw bag contains two extra nuts, but two washers are not included.",
        "The screw bag detected an extra washer, but a nut is missing.",
        "The screw bag contains an additional nut, but a washer is missing."
    ],
    "structural_anomalies":
    [
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag is damaged.",
        "The screw bag has a fractured washer.",
        "The screw bag has a fractured washer.",
        "The screw bag has a fractured washer.",
        "The screw bag has a fractured nut.",
        "The screw bag has a fractured short screw.",
        "The screw bag has a fractured long screw.",
        "The screw bag has a fractured short screw.",
        "The screw bag has a fractured nut.",
        "The screw bag has a fractured short screw.",
        "The screw bag has a fractured nut.",
        "The screw bag has a fractured short screw.",
        "The screw bag has a fractured washer.",
        "The screw bag has a fractured nut.",
        "The screw bag has a fractured nut.",
        "The screw bag has a fractured long screw.",
        "The screw bag has a fractured short screw.",
        "The screw bag has a fractured washer.",
        "The screw bag has a fractured nut.",
        "The screw bag has a fractured long screw.",
        "The screw bag has a fractured short screw.",
        "The screw bag has a fractured nut.",
        "The screw bag has a fractured long screw.",
        "The screw bag has a fractured washer.",
        "The screw bag has a fractured washer.",
        "The screw bag has a fractured short screw.",
        "The screw bag has a nut with green paint contamination.",
        "The screw bag has a long screw with green paint contamination.",
        "The screw bag has a short screw with red paint contamination.",
        "The screw bag has a nut with green paint contamination.",
        "The screw bag has a long screw with green paint contamination.",
        "The screw bag has a nut with red paint contamination.",
        "The screw bag has a washer with green paint contamination.",
        "The screw bag has a short screw with green paint contamination.",
        "The screw bag has a long screw with green paint contamination.",
        "The screw bag has a bag with green paint contamination.",
        "The screw bag has a short screw with green paint contamination.",
        "The screw bag has a washer with green paint contamination.",
        "The screw bag has a washer with green paint contamination.",
        "The screw bag has a short screw with red paint contamination.",
        "The screw bag has a washer with green paint contamination.",
        "The screw bag has a long screw with green paint contamination.",
        "A gold-colored nut mixed in the screw bag.",
        "A yellow-striped object mixed in the screw bag.",
        "A screw mixed in the screw bag.",
        "A screw mixed in the screw bag.",
        "A big washer mixed in the screw bag.",
        "A gold-colored screw mixed in the screw bag.",
        "A big nut mixed in the screw bag.",
        "A nail mixed in the screw bag.",
        "A nail mixed in the screw bag.",
        "A rectangular bar-shaped nut mixed in the screw bag.",
        "A black short screw mixed in the screw bag.",
        "A double nut-like object mixed in the screw bag.",
        "A nut with serrated edges mixed in the screw bag.",
        "A small washer mixed in the screw bag.",
        "An unidentified small object mixed in the screw bag.",
        "A nut with serrated edges mixed in the screw bag.",
        "An unspecified anomaly object mixed in the screw bag.",
        "An unidentified small object mixed in the screw bag.",
        "A large washer with serrated edges mixed in the screw bag.",
        "An anomaly black nail mixed in the screw bag.",
        "An unspecified anomaly object mixed in the screw bag.",
        "A big washer mixed in the screw bag.",
        "A washer with serrated edges anomaly mixed in the screw bag.",
        "A nut with serrated edges mixed in the screw bag.",
        "A nail mixed in the screw bag."
    ]
}

splicing_connectors={
    "logical_anomalies":
    [
        "A cable is severed.",
        "A cable is severed.",
        "A cable is severed.",
        "A cable is severed.",
        "A cable is severed.",
        "A cable is severed.",
        "A cable is severed.",
        "A cable is severed.",
        "A cable is severed.",
        "A cable is severed.",
        "A cable is severed.",
        "A cable is severed.",
        "The two-pin connector is incorrectly connected to the five-pin connector.",
        "The two-pin connector is incorrectly connected to the five-pin connector.",
        "The two-pin connector is incorrectly connected to the three-pin connector.",
        "The three-pin connector is incorrectly connected to the five-pin connector.",
        "The two-pin connector is incorrectly connected to the five-pin connector.",
        "The two-pin connector is incorrectly connected to the five-pin connector.",
        "The two-pin connector is incorrectly connected to the three-pin connector.",
        "The two-pin connector is incorrectly connected to the three-pin connector.",
        "The two-pin connector is incorrectly connected to the five-pin connector.",
        "A cable is missing.",
        "A cable is missing.",
        "A cable is missing.",
        "A cable is missing.",
        "A cable is missing.",
        "A cable is missing.",
        "A cable is missing.",
        "A cable is missing.",
        "A cable is missing.",
        "A cable is missing.",
        "A cable is missing.",
        "A cable is missing.",
        "Both connector and cable are missing.",
        "Both connector and cable are missing.",
        "A five-pin connector is missing.",
        "A two-pin connector is missing.",
        "A two-pin connector is missing.",
        "A three-pin connector is missing.",
        "A five-pin connector is missing.",
        "A five-pin connector is missing.",
        "A two-pin connector is missing.",
        "A three-pin connector is missing.",
        "A three-pin connector is missing.",
        "A two-pin connector is missing.",
        "A five-pin connector is missing.",
        "A three-pin connector is missing.",
        "An extra cable is included.",
        "An extra cable is included.",
        "An extra cable is included.",
        "An extra cable is included.",
        "An extra cable is included.",
        "An extra cable is included.",
        "An extra cable is included.",
        "An extra cable is included.",
        "An extra cable is included.",
        "An extra cable is included.",
        "An extra cable is included.",
        "An extra cable is included.",
        "The cable is too short.",
        "The cable is too short.",
        "The cable is too short.",
        "The cable is too short.",
        "The cable is too short.",
        "The cable is too short.",
        "The cable is too short.",
        "The cable is too short.",
        "The cable is too short.",
        "The cable is too short.",
        "The cable is too short.",
        "The cable is too short.",
        "A two-pin connector is incorrectly connected to a blue cable.",
        "A two-pin connector is incorrectly connected to a red cable.",
        "A three-pin connector is incorrectly connected to a red cable.",
        "A two-pin connector is incorrectly connected to a red cable.",
        "A three-pin connector is incorrectly connected to a red cable.",
        "A five-pin connector is incorrectly connected to a yellow cable.",
        "A five-pin connector is incorrectly connected to a blue cable.",
        "A three-pin connector is incorrectly connected to a yellow cable.",
        "A three-pin connector is incorrectly connected to a yellow cable.",
        "A two-pin connector is incorrectly connected to a blue cable.",
        "A five-pin connector is incorrectly connected to a blue cable.",
        "A five-pin connector is incorrectly connected to a yellow cable.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector.",
        "The cable is connected to the wrong port of the connector."
    ],
    "structural_anomalies":
    [
        "The yellow cable is fractured.",
        "The blue cable is fractured.",
        "The yellow cable is fractured.",
        "The yellow cable is fractured.",
        "The blue cable is fractured.",
        "The blue cable is fractured.",
        "The yellow cable is fractured.",
        "The yellow cable is fractured.",
        "The red cable is fractured.",
        "The blue cable is fractured.",
        "The red cable is fractured.",
        "The red cable is fractured.",
        "The connector is broken.",
        "The connector is broken.",
        "The connector is broken.",
        "The connector is broken.",
        "The connector is broken.",
        "The connector is broken.",
        "The connector is broken.",
        "The connector is broken.",
        "The connector is broken.",
        "The connector is broken.",
        "The connector is broken.",
        "The connector is broken.",
        "The cable is not securely connected.",
        "The cable is not securely connected.",
        "The cable is not securely connected.",
        "The cable is not securely connected.",
        "The cable is not securely connected.",
        "The cable is not securely connected.",
        "The cable is not securely connected.",
        "The cable is not securely connected.",
        "The cable is not securely connected.",
        "A connector is contaminated with red paint.",
        "A cable is contaminated with black paint.",
        "A cable is contaminated with black paint.",
        "A cable is contaminated with black paint.",
        "A connector is contaminated with black paint.",
        "A cable is contaminated with black paint.",
        "A cable is contaminated with black paint.",
        "A cable is contaminated with red paint.",
        "A cable is contaminated with black paint.",
        "A cable is contaminated with red paint.",
        "A cable is contaminated with red paint.",
        "A fractured red cable is mixed in.",
        "A fractured yellow cable is mixed in.",
        "A metal object is mixed in.",
        "A metal object is mixed in.",
        "A broken connector is mixed in.",
        "A two-pin connector is mixed in.",
        "A two-pin connector is mixed in.",
        "A washer is mixed in.",
        "A washer is mixed in.",
        "A fractured yellow cable is mixed in.",
        "A washer is mixed in.",
        "A five-pin connector is flipped.",
        "A three-pin connector is flipped.",
        "A three-pin connector is flipped.",
        "A five-pin connector is flipped.",
        "A five-pin connector is flipped.",
        "A three-pin connector is flipped.",
        "A three-pin connector is flipped.",
        "A two-pin connector is flipped.",
        "A two-pin connector is flipped.",
        "A two-pin connector is flipped.",
        "A five-pin connector is flipped.",
        "A two-pin connector is flipped.",
        "The cable has an unknown color outside of red, yellow, or blue.",
        "The cable has an unknown color outside of red, yellow, or blue.",
        "The cable has an unknown color outside of red, yellow, or blue.",
        "The cable has an unknown color outside of red, yellow, or blue.",
        "The cable has an unknown color outside of red, yellow, or blue.",
        "The cable has an unknown color outside of red, yellow, or blue.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position.",
        "The lever of the connector is in the open position."
    ]
}

categories = {
    "breakfast_box": breakfast_box,
    "juice_bottle":juice_bottle,
    "pushpins":pushpins,
    "screw_bag":screw_bag,
    "splicing_connectors":splicing_connectors
}


####-----------------------------合并mask-------------------------------

from PIL import Image
import os
import numpy as np

mvtec_loco_anomaly_path = "./datasets/mvtec_loco_anomaly_detection"
entries = os.listdir(mvtec_loco_anomaly_path)
samples = [entry for entry in entries if os.path.isdir(os.path.join(mvtec_loco_anomaly_path, entry))]
anomaly_list = ["logical_anomalies", "structural_anomalies"]
ground_truth_merge_mask_name = "ground_truth_merge_mask"

for sample in samples:
    for anomaly in anomaly_list:

        base_path = os.path.join(mvtec_loco_anomaly_path, sample, "ground_truth", anomaly)

        entries = os.listdir(base_path)
        # Input folder path
        for idx_file in entries:
            folder_path = os.path.join(mvtec_loco_anomaly_path, sample, "ground_truth", anomaly, idx_file)
            # Get all image filenames within the folder
            image_files = [f for f in os.listdir(folder_path) if f.endswith('.png') or f.endswith('.jpg')]

            # Use the first image as the initial image
            initial_image_path = os.path.join(folder_path, image_files[0])
            initial_image = Image.open(initial_image_path)

            # Convert the initial image to a numpy array for further operations
            initial_image_array = np.array(initial_image)

            if len(image_files) > 1:
                # Iterate through the remaining images, adding white pixels to the initial image
                for image_file in image_files[1:]:
                    image_path = os.path.join(folder_path, image_file)
                    image = Image.open(image_path)
                    # Convert the image to a numpy array for processing
                    image_array = np.array(image)
                    # Find coordinates of the white pixel parts
                    white_pixels = np.where(image_array > 245)
                    # Add the white pixel parts to the initial image
                    initial_image_array[white_pixels] = 255
                print("Checking masks to merge for", sample, anomaly, idx_file)
            # Convert the merged numpy array back to an image
            merged_image = Image.fromarray(initial_image_array)

            directory = os.path.join(mvtec_loco_anomaly_path, sample, ground_truth_merge_mask_name, anomaly + "_merge_mask")
            if not os.path.exists(directory):
                os.makedirs(directory)
            # Save the merged image
            merged_image.save(os.path.join(directory, idx_file + ".png"))





####-----------------------------Generate Prompts-------------------------------

mvtec_loco_datasets_path = mvtec_loco_anomaly_path + "/"

# Get all entry names under mvtec_loco_datasets_path
samples = os.listdir(mvtec_loco_datasets_path)
samples_list = []
for sample in samples:
    sample_path = os.path.join(mvtec_loco_datasets_path, sample)
    if os.path.isdir(sample_path):
        samples_list.append(sample)

# Iterate through each sample
for sample in samples_list:
    print("-------------------------------------------------------------")
    sample_path = os.path.join(mvtec_loco_datasets_path, sample)  # Construct full entry path

    source_dir = os.path.join(sample_path, 'ground_truth')  # Source directory path
    target_dir = os.path.join(sample_path, 'prompt')  # Target directory path

    os.makedirs(target_dir, exist_ok=True)  # Create target directory: prompt

    # Iterate over the source GT directory ['logical_anomaly', 'structural_anomalies']
    source_dir_list = os.listdir(source_dir)
    for anomaly_name in source_dir_list:
        target_path = os.path.join(target_dir, anomaly_name)
        os.makedirs(target_path, exist_ok=True)  # e.g., breakfast/prompt/logical_anomaly

        anomaly_png = os.listdir(os.path.join(source_dir, anomaly_name))
        nums = len(anomaly_png)

        anomaly_dir = categories[sample]  # Get the anomaly prompt corresponding to the sample

        # Check for alignment
        print("Preparing to generate prompts for", anomaly_name)

        if (nums == len(anomaly_dir[anomaly_name])):
            print(sample + " " + anomaly_name + ": correct number of prompts, starting prompt generation, total", nums)

            if anomaly_name in anomaly_dir:
                prompt_lists = anomaly_dir[anomaly_name]
                for idx in range(nums):
                    txt_idx = str(idx).zfill(3)
                    target_txt_path = os.path.join(target_path, txt_idx)
                    target_txt_path_name = target_txt_path + ".txt"
                    os.makedirs(os.path.dirname(target_txt_path_name), exist_ok=True)
                    # Check if the prompt is in the standard format xxx, xxx, xxx
                    parts = [part.strip() for part in prompt_lists[idx].split(",")]
                    if "" in parts:
                        print(prompt_lists[idx], "is not in the standard format")

                    with open(target_txt_path_name, 'w') as file:
                        file.write(prompt_lists[idx])  # Create a text file with the prompt

        else:
            print(sample, " ", anomaly_name + " prompt count: ", len(anomaly_dir[anomaly_name]), ", ", anomaly_name, " GT count: ", nums, ", counts do not match")
