import os
import shutil


bottle={
    "broken_large":[
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken.",
        "The bottle has a large broken."
    ],
    "broken_small":[
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken.",
        "The bottle has a small broken."
    ],
    "contamination":[
        "The bottle has contamination with white filler.",
        "The bottle has contamination with white filler.",
        "The bottle has contamination with white filler.",
        "The bottle has contamination with a gel-like substance.",
        "The bottle has contamination with a gel-like substance.",
        "The bottle has contamination with white filler and brown filler.",
        "The bottle has contamination with white filler and brown filler.",
        "The bottle has contamination with red and black woven fabric.",
        "The bottle has contamination with a transparent foreign filler.",
        "The bottle has contamination with a transparent foreign filler.",
        "The bottle has contamination with a transparent foreign filler.",
        "The bottle has contamination with a transparent foreign filler and brown filler.",
        "The bottle has contamination with brown filler.",
        "The bottle has contamination with a linear strip.",
        "The bottle has contamination with a linear strip.",
        "The bottle has contamination with a rough line.",
        "The bottle has contamination with brown filler.",
        "The bottle has contamination with black woven fabric.",
        "The bottle has contamination with a white linear strip.",
        "The bottle has contamination with a gel-like substance.",
        "The bottle has contamination with brown filler."
    ]
}

cable = {
    "bent_wire": [
        "The blue cable has bent wire.",
        "The blue cable has bent wire.",
        "The green cable has bent wire.",
        "The gray cable has bent wire.",
        "The gray cable has bent wire.",
        "The green cable has bent wire.",
        "The blue cable has bent wire.",
        "The green cable has bent wire.",
        "The green cable has bent wire.",
        "The blue cable has bent wire.",
        "The gray cable has bent wire.",
        "Both the green and blue cables have bent wires.",
        "Both the green and blue cables have bent wires."
    ],
    "cable_swap": [
        "The gray cable is replaced by a repeated blue cable.",
        "The green cable is replaced by a repeated blue cable.",
        "The blue cable is replaced by a repeated green cable.",
        "The gray cable is replaced by a repeated green cable.",
        "The green cable is replaced by a repeated gray cable.",
        "The blue cable is replaced by a repeated green cable.",
        "The gray cable is replaced by a repeated blue cable.",
        "The blue cable is replaced by a repeated gray cable.",
        "The green cable is replaced by a repeated blue cable.",
        "The gray cable is replaced by a repeated blue cable.",
        "The blue cable is replaced by a repeated green cable.",
        "The green cable is replaced by a repeated gray cable."
    ],
    "combined": [
        "The green cable has bent wire, and the insulation is poked.",
        "The blue cable has bent wire, and the outer insulation is cut.",
        "The insulation is poked, and the outer insulation is cut.",
        "The insulation is poked, and the wire in the green cable is missing, replaced by a black hole.",
        "The blue inner insulation is cut, and the outer insulation is cut.",
        "The blue cable is replaced by a repeated blue cable, and one green cable is missing, replaced by a black hole.",
        "One green cable is missing, replaced by a black hole, and the wire in the blue cable is missing, replaced by a black hole.",
        "The green cable is replaced by a repeated green cable, and the wire in the green cable is missing, replaced by a black hole.",
        "The green cable has bent wire, and the wire in the gray cable is missing, replaced by a black hole.",
        "The blue cable is replaced by a repeated blue cable, and the gray inner insulation is cut.",
        "One blue cable is missing, replaced by a black hole, and the outer insulation is cut."
    ],
    "cut_inner_insulation": [
        "The gray inner insulation is cut.",
        "The blue inner insulation is cut.",
        "The gray inner insulation is cut.",
        "The gray and green inner insulations are cut.",
        "The gray inner insulation is cut.",
        "The green inner insulation is cut.",
        "The blue inner insulation is cut.",
        "The gray and green inner insulations are cut.",
        "The gray inner insulation is cut.",
        "The gray and green inner insulations are cut.",
        "The green inner insulation is cut.",
        "The blue inner insulation is cut.",
        "The gray, green, and blue inner insulations are cut.",
        "The green inner insulation is cut."
    ],
    "cut_outer_insulation": [
        "The outer insulation is cut.",
        "The outer insulation is cut.",
        "The outer insulation is cut.",
        "The outer insulation is cut.",
        "The outer insulation is cut.",
        "The outer insulation is cut.",
        "The outer insulation is cut.",
        "The outer insulation is cut.",
        "The outer insulation is cut.",
        "The outer insulation is cut."
    ],
    "missing_cable": [
        "One green cable is missing, replaced by a black hole.",
        "One blue cable is missing, replaced by a black hole.",
        "One blue cable is missing, replaced by a black hole.",
        "One blue cable is missing, replaced by a black hole.",
        "One gray cable is missing, replaced by a black hole.",
        "One gray cable is missing, replaced by a black hole.",
        "One gray cable, one blue cable, and one green cable are missing, each replaced by a black hole.",
        "One gray cable and one green cable are missing, each replaced by a black hole.",
        "One gray cable and one blue cable are missing, each replaced by a black hole.",
        "One blue cable and one green cable are missing, each replaced by a black hole.",
        "One green cable is missing, replaced by a black hole.",
        "One green cable is missing, replaced by a black hole."
    ],
    "missing_wire": [
        "The wire in the blue cable is missing, replaced by a black hole.",
        "The wire in the green cable is missing, replaced by a black hole.",
        "The wire in the blue cable is missing, replaced by a black hole.",
        "The wires in the gray and green cables are missing, each replaced by a black hole.",
        "The wires in the gray and blue cables are missing, each replaced by a black hole.",
        "The wire in the gray cable is missing, replaced by a black hole.",
        "The wire in the green cable is missing, replaced by a black hole.",
        "The wire in the blue cable is missing, replaced by a black hole.",
        "The wire in the gray cable is missing, replaced by a black hole.",
        "The wire in the green cable is missing, replaced by a black hole."
    ],
    "poke_insulation": [
        "The insulation is poked.",
        "The insulation is poked.",
        "The insulation is poked.",
        "The insulation is poked.",
        "The insulation is poked.",
        "The insulation is poked.",
        "The insulation is poked.",
        "The insulation is poked.",
        "The insulation is poked.",
        "The insulation is poked."
    ],
}

capsule = {
    "crack": [
        "The red section of the capsule has cracked.",
        "The black section of the capsule has cracked.",
        "The black section of the capsule has cracked.",
        "The red section of the capsule has cracked.",
        "The red section of the capsule has cracked.",
        "The black section of the capsule has cracked.",
        "The red section of the capsule has cracked.",
        "The red section of the capsule has cracked.",
        "The red section of the capsule has cracked.",
        "The red section of the capsule has cracked.",
        "The black section of the capsule has cracked.",
        "The black section of the capsule has cracked.",
        "The black section and the red section of the capsule have cracked.",
        "The black section of the capsule has cracked.",
        "The black section of the capsule has cracked.",
        "The black section of the capsule has cracked.",
        "The red section of the capsule has cracked.",
        "The red section of the capsule has cracked.",
        "The red section of the capsule has cracked.",
        "The red section of the capsule has cracked.",
        "The black section of the capsule has cracked.",
        "The black section of the capsule has cracked.",
        "The red section of the capsule has cracked."
    ],
    "faulty_imprint": [
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule is missing imprint.",
        "The capsule is missing imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint.",
        "The capsule has an incorrect imprint."
    ],
    "poke": [
        "The red section of the capsule has an anomaly poke.",
        "The black section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The black section of the capsule has an anomaly poke.",
        "The black section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The black section and the red section of the capsule have an anomaly poke.",
        "The black section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The black section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The black section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke.",
        "The red section of the capsule has an anomaly poke."
    ],
    "scratch": [
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The black section of the capsule has an anomaly scratch.",
        "The red and black sections of the capsule have anomaly scratches.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch.",
        "The red section of the capsule has an anomaly scratch."
    ],
    "squeeze": [
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed.",
        "The capsule has been squeezed."
    ],
}

carpet = {
    "color": [
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly.",
        "The carpet has a black anomaly."
    ],
    "cut": [
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut.",
        "The carpet has been cut."
    ],
    "hole": [
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole.",
        "The carpet has a anomaly hole."
    ],
    "metal_contamination": [
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet.",
        "There is a anomaly metal contamination on the carpet."
    ],
    "thread": [
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal black thread on the carpet.",
        "There is an abnormal black thread on the carpet.",
        "There is an abnormal black thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal black thread on the carpet.",
        "There is an abnormal black thread on the carpet.",
        "There is an abnormal thread on the carpet.",
        "There is an abnormal thread on the carpet."
    ],
}

grid = {
    "bent":[
        "The grid has bent.",
        "The grid has bent.",
        "The grid has bent.",
        "The grid has bent.",
        "The grid has bent.",
        "The grid has bent.",
        "The grid has bent.",
        "The grid has bent.",
        "The grid has bent.",
        "The grid has bent.",
        "The grid has bent.",
        "The grid has bent."
    ],
    "broken":[
        "The grid has broken.",
        "The grid has broken.",
        "The grid has broken.",
        "The grid has broken.",
        "The grid has broken.",
        "The grid has broken.",
        "The grid has broken.",
        "The grid has broken.",
        "The grid has broken.",
        "The grid has broken.",
        "The grid has broken.",
        "The grid has broken."
    ],
    "glue":[
        "There is glue on the grid.",
        "There is glue on the grid.",
        "There is glue on the grid.",
        "There is glue on the grid.",
        "There is glue on the grid.",
        "There is glue on the grid.",
        "There is glue on the grid.",
        "There is glue on the grid.",
        "There is glue on the grid.",
        "There is glue on the grid.",
        "There is glue on the grid."
    ],
    "metal_contamination":[
        "There is a anomaly metal contamination on the grid.",
        "There is a anomaly metal contamination on the grid.",
        "There is a anomaly metal contamination on the grid.",
        "There is a anomaly metal contamination on the grid.",
        "There is a anomaly metal contamination on the grid.",
        "There is a anomaly metal contamination on the grid.",
        "There is a anomaly metal contamination on the grid.",
        "There is a anomaly metal contamination on the grid.",
        "There is a anomaly metal contamination on the grid.",
        "There is a anomaly metal contamination on the grid.",
        "There is a anomaly metal contamination on the grid."
    ],
    "thread":[
        "There is some abnormal thread on the grid.",
        "There is some abnormal thread on the grid.",
        "There is an abnormal straight thread on the grid.",
        "There is an abnormal straight thread on the grid.",
        "There is an abnormal straight thread on the grid.",
        "There is an abnormal straight thread on the grid.",
        "There is an abnormal straight thread on the grid.",
        "There is an abnormal straight thread on the grid.",
        "There is an abnormal straight thread on the grid.",
        "There is an abnormal straight thread on the grid.",
        "There is an abnormal straight thread on the grid."
    ]
}

hazelnut={
    "crack": [
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked.",
        "The hazelnut is cracked.",
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked.",
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked.",
        "The hazelnut is cracked.",
        "The hazelnut is cracked.",
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked and broken.",
        "The hazelnut is cracked and broken."
    ],
    "cut": [
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks.",
        "The hazelnut has cut marks."
    ],
    "hole": [
        "The hazelnut has a hole.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole and a crack.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole and a crack.",
        "The hazelnut has a hole and a crack.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole and a crack.",
        "The hazelnut has a hole.",
        "The hazelnut has a hole and a crack.",
        "The hazelnut has a hole."
    ],
    "print": [
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print.",
        "The hazelnut has a anomaly white print."
    ]
}

leather={
    "color": [
        "There is a gray stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather.",
        "There is a red stain on the leather."
    ],
    "cut": [
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut.",
        "The leather has been cut."
    ],
    "fold": [
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark.",
        "The leather has a fold mark."
    ],
    "glue": [
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather.",
        "There is glue on the leather."
    ],
    "poke": [
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather.",
        "There is poke on the leather."
    ]
}

metal_nut={
    "bent": [
        "The metal nut is bent downward.",
        "The metal nut is bent downward.",
        "The metal nut is bent downward.",
        "The metal nut is bent downward.",
        "The metal nut is bent downward.",
        "The metal nut is bent downward.",
        "The metal nut is bent downward.",
        "The metal nut is bent downward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent downward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent downward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward.",
        "The metal nut is bent upward."
    ],
    "color": [
        "The metal nut has a black contamination.",
        "The metal nut has a blue contamination.",
        "The metal nut has a blue contamination.",
        "The metal nut has a blue contamination.",
        "The metal nut has a blue contamination.",
        "The metal nut has a blue contamination.",
        "The metal nut has a black contamination.",
        "The metal nut has a black contamination.",
        "The metal nut has a black contamination.",
        "The metal nut has a black contamination.",
        "The metal nut has a black contamination.",
        "The metal nut has a black contamination.",
        "The metal nut has a red contamination.",
        "The metal nut has a red contamination.",
        "The metal nut has a red contamination.",
        "The metal nut has a red contamination.",
        "The metal nut has a blue contamination.",
        "The metal nut has a blue contamination.",
        "The metal nut has a blue contamination.",
        "The metal nut has a red contamination.",
        "The metal nut has a red contamination.",
        "The metal nut has a black contamination."
    ],
    "flip": [
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped.",
        "The metal nut has flipped."
    ],
    "scratch": [
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch.",
        "The metal nut has scratch."
    ]
}

pill = {
    "color":[
        "The pill has a red contamination.",
        "The pill has a yellow contamination.",
        "The pill has a yellow contamination.",
        "The pill has a yellow contamination.",
        "The pill has a yellow contamination.",
        "The pill has a red contamination.",
        "The pill has a red contamination.",
        "The pill has a red contamination.",
        "The pill has a blue contamination.",
        "The pill has a blue contamination.",
        "The pill has a blue contamination.",
        "The pill has a blue contamination.",
        "The pill has a blue contamination.",
        "The pill has a blue contamination.",
        "The pill has a red contamination.",
        "The pill has a blue contamination.",
        "The pill has a red contamination.",
        "The pill has a red contamination.",
        "The pill has a red contamination.",
        "The pill has a red contamination.",
        "The pill has a red contamination.",
        "The pill has a red contamination.",
        "The pill has a yellow contamination.",
        "The pill has a yellow contamination.",
        "The pill has a red contamination."
    ],
    "combined":[
        "The pill has a scratch and a red contamination.",
        "The pill has a faulty imprint and a crack.",
        "The pill has a yellow contamination and a crack.",
        "The pill has a white contamination and a blue contamination.",
        "The pill has a white contamination, a red contamination and a crack.",
        "The pill has a red contamination and a crack.",
        "The pill has a faulty imprint and a scratch.",
        "The pill has a red contamination and a faulty imprint.",
        "The pill has a white contamination and a crack.",
        "The pill has a yellow contamination and a crack.",
        "The pill has a red contamination and a faulty imprint.",
        "The pill has a scratch and a crack.",
        "The pill has a black contamination and a crack.",
        "The pill has a crack.",
        "The pill has red, yellow, and black contamination.",
        "The pill has a scratch and a crack.",
        "The pill has a white contamination and a crack."
    ],
    "contamination":[
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination.",
        "The pill has a white contamination."
    ],
    "crack":[
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack.",
        "The pill has a crack."
    ],
    "faulty_imprint":[
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint.",
        "The pill has a faulty imprint."
    ],
    "pill_type":[
        "The pill has dense red small spots.",
        "The pill has dense red small spots.",
        "The pill has sparse yellow large spots.",
        "The pill has sparse yellow large spots.",
        "The pill has sparse yellow large spots.",
        "The pill has dense red small spots.",
        "The pill has dense red small spots.",
        "The pill has sparse yellow large spots.",
        "The pill has sparse yellow large spots."
    ],
    "scratch":[
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch.",
        "The pill has scratch."
    ]
}

screw={
    "manipulated_front":[
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired.",
        "The front end of the screw is impaired."
    ],
    "scratch_head":[
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired.",
        "The screw head is impaired."
    ],
    "scratch_neck":[
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired.",
        "The screw neck is impaired."
    ],
    "thread_side":[
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired.",
        "The screw thread side is impaired."
    ],
    "thread_top":[
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired.",
        "The screw thread top is impaired."
    ]
}

tile={
    "crack":[
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack.",
        "The tile has crack."
    ],
    "glue_strip":[
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile.",
        "There is a glue strip on the tile."
    ],
    "gray_stroke":[
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke.",
        "The tile has a black stroke."
    ],
    "oil":[
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it.",
        "The tile has oil on it."
    ],
    "rough":[
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture.",
        "The tile has a rough texture."
    ]
}

toothbrush={
    "defective":[
        "The blue toothbrush has frayed bristles and an anomaly white object.",
        "The blue toothbrush has missing bristles.",
        "The blue toothbrush has missing and frayed bristles.",
        "The blue toothbrush has linear defects and missing bristles.",
        "The blue toothbrush has linear defects.",
        "The blue toothbrush has frayed bristles.",
        "The blue toothbrush has frayed bristles.",
        "The blue toothbrush has missing bristles.",
        "The blue toothbrush has frayed bristles.",
        "The blue toothbrush has linear defects and a crack.",
        "The red toothbrush has frayed bristles.",
        "The red toothbrush has missing bristles.",
        "The red toothbrush has missing and frayed bristles.",
        "The red toothbrush has an anomaly white object.",
        "The red toothbrush has frayed bristles and an anomaly white object.",
        "The red toothbrush has linear defects.",
        "The red toothbrush has missing and frayed bristles.",
        "The red toothbrush has frayed bristles and linear defects.",
        "The red toothbrush has missing bristles and linear defects.",
        "The red toothbrush has linear defects and frayed bristles.",
        "The yellow toothbrush has an anomaly white object.",
        "The yellow toothbrush has missing bristles.",
        "The yellow toothbrush has frayed bristles.",
        "The yellow toothbrush has frayed bristles.",
        "The yellow toothbrush has missing bristles.",
        "The yellow toothbrush has frayed bristles.",
        "The yellow toothbrush has frayed bristles.",
        "The yellow toothbrush has missing bristles.",
        "The yellow toothbrush has missing bristles.",
        "The yellow toothbrush has frayed bristles."
    ]
}

transistor={
    "bent_lead":[
        "The transistor has bent lead.",
        "The transistor has bent lead.",
        "The transistor has bent lead.",
        "The transistor has bent lead.",
        "The transistor has bent lead.",
        "The transistor has bent lead.",
        "The transistor has bent lead.",
        "The transistor has bent lead.",
        "The transistor has bent lead.",
        "The transistor has bent lead."
    ],
    "cut_lead":[
        "The lead of the transistor has been cut.",
        "The lead of the transistor has been cut.",
        "The lead of the transistor has been cut.",
        "The lead of the transistor has been cut.",
        "The lead of the transistor has been cut.",
        "The lead of the transistor has been cut.",
        "The lead of the transistor has been cut.",
        "The lead of the transistor has been cut.",
        "The lead of the transistor has been cut.",
        "The lead of the transistor has been cut."
    ],
    "damaged_case":[
        "The transistor is damaged.",
        "The transistor is damaged.",
        "The transistor is damaged.",
        "The transistor is damaged.",
        "The transistor is damaged.",
        "The transistor is damaged.",
        "The transistor is damaged.",
        "The transistor is damaged.",
        "The transistor is damaged.",
        "The transistor is damaged."
    ],
    "misplaced":[
        "The transistor is misplaced.",
        "The transistor is misplaced.",
        "The transistor is missing.",
        "The transistor is missing.",
        "The transistor is misplaced.",
        "The transistor is misplaced.",
        "The transistor is misplaced.",
        "The transistor is misplaced.",
        "The transistor is misplaced.",
        "The transistor is misplaced."
    ]
}

wood={
    "color":[
        "The wood is contaminated with red stains.",
        "The wood is contaminated with purple stains.",
        "The wood is contaminated with purple stains.",
        "The wood is contaminated with black stains.",
        "The wood is contaminated with red stains.",
        "The wood is contaminated with black stains.",
        "The wood is contaminated with red stains.",
        "The wood is contaminated with red stains."
    ],
    "combined":[
        "The wood has holes and scratch.",
        "The wood has holes and scratch.",
        "The wood has holes and scratch.",
        "The wood has wood shavings.",
        "The wood has holes.",
        "The wood has holes and red stains.",
        "The wood has holes.",
        "The wood has holes and red stains.",
        "The wood has holes and scratch.",
        "The wood has holes.",
        "The wood has holes and red stains."
    ],
    "hole":[
        "The wood has holes.",
        "The wood has holes.",
        "The wood has holes.",
        "The wood has holes.",
        "The wood has holes and a crack.",
        "The wood has a crack.",
        "The wood has holes.",
        "The wood has holes.",
        "The wood has holes.",
        "The wood has holes."
    ],
    "liquid":[
        "The wood has liquid on it.",
        "The wood has liquid on it.",
        "The wood has liquid on it.",
        "The wood has liquid on it.",
        "The wood has liquid on it.",
        "The wood has liquid on it.",
        "The wood has liquid on it.",
        "The wood has liquid on it.",
        "The wood has liquid on it.",
        "The wood has liquid on it."
    ],
    "scratch":[
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch.",
        "The wood has scratch."
    ]
}

zipper={
    "broken_teeth":[
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth.",
        "The zipper has broken teeth."
    ],
    "combined":[
        "The zipper has split and broken teeth.",
        "The zipper has split and broken teeth.",
        "The zipper's teeth are split and squeezed.",
        "The zipper's fabric border and interior are damaged.",
        "The zipper's fabric border and interior are damaged, and its teeth are squeezed.",
        "The zipper's teeth are squeezed and rough.",
        "The zipper's fabric border is damaged and its teeth are rough.",
        "The zipper's teeth are squeezed and its fabric interior is damaged.",
        "The zipper's teeth are rough and its fabric interior is damaged.",
        "The zipper's teeth are rough and its fabric interior is damaged.",
        "The zipper has broken teeth and its fabric border is damaged.",
        "The zipper's fabric border and interior are damaged.",
        "The zipper's teeth are squeezed and its fabric interior is damaged.",
        "The zipper's teeth are squeezed and its fabric border is damaged.",
        "The zipper has split and broken teeth, and its fabric interior is damaged.",
        "The zipper has split and broken teeth, and its fabric border is damaged."
    ],
    "fabric_border":[
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged.",
        "The zipper's fabric border is damaged."
    ],
    "fabric_interior":[
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged.",
        "The zipper's fabric interior is damaged."
    ],
    "rough":[
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough.",
        "The zipper's teeth are rough."
    ],
    "split_teeth":[
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split.",
        "The zipper's teeth are split."
    ],
    "squeezed_teeth":[
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed.",
        "The zipper's teeth are squeezed."
    ]
}

categories = {
    "bottle": bottle,
    "cable":cable,
    "capsule":capsule,
    "carpet":carpet,
    "grid":grid,
    "hazelnut":hazelnut,
    "leather":leather,
    "metal_nut":metal_nut,
    "pill":pill,
    "screw":screw,
    "tile":tile,
    "toothbrush":toothbrush,
    "transistor":transistor,
    "wood":wood,
    "zipper":zipper
}

mvtec_datasets_path = './datasets/mvtec_anomaly_detection/'

# Get the names of all entries under mvtec_datasets_path
samples = os.listdir(mvtec_datasets_path)
samples_list = []
for sample in samples:
    sample_path = os.path.join(mvtec_datasets_path, sample)
    if os.path.isdir(sample_path):
        samples_list.append(sample)

# Iterate through each sample
for sample in samples_list:  # bottle
    print("-------------------------------------------------------------")
    # Complete entry path for the sample
    sample_path = os.path.join(mvtec_datasets_path, sample)

    # Source directory path
    source_dir = os.path.join(sample_path, 'ground_truth')

    # Target directory path
    target_dir = os.path.join(sample_path, 'prompt')

    os.makedirs(target_dir, exist_ok=True)  # Create target directory: prompt

    # Traverse the source GT directory ['contamination', 'broken_large', 'broken_small']
    source_dir_list = os.listdir(source_dir)
    for anomaly_name in source_dir_list:  # anomaly contamination
        target_path = os.path.join(target_dir, anomaly_name)
        os.makedirs(target_path, exist_ok=True)

        anomaly_png = os.listdir(os.path.join(source_dir, anomaly_name))
        nums = len(anomaly_png)

        anomaly_dir = categories[sample]  # Get the corresponding anomaly prompt for the sample

        # Check for alignment
        print("Preparing to generate", anomaly_name, "prompt")

        if (nums == len(anomaly_dir[anomaly_name])):
            print(sample + " " + anomaly_name + ": prompt count is correct, beginning prompt generation, total", nums, "items")

            if anomaly_name in anomaly_dir:
                prompt_lists = anomaly_dir[anomaly_name]
                for idx in range(nums):
                    txt_idx = str(idx).zfill(3)
                    target_txt_path = os.path.join(target_path, txt_idx)
                    target_txt_path_name = target_txt_path + ".txt"
                    os.makedirs(os.path.dirname(target_txt_path_name), exist_ok=True)
                    # Check if the prompt is in the standard format xxx, xxx, xxx
                    parts = [part.strip() for part in prompt_lists[idx].split(",")]
                    if "" in parts:
                        print(prompt_lists[idx], "is not in the standard format")

                    with open(target_txt_path_name, 'w') as file:
                        file.write(prompt_lists[idx])  # Create an empty text file

        else:
            print(sample + " " + anomaly_name + " prompt count is:", len(anomaly_dir[anomaly_name]), ",", anomaly_name, "GT count is:", nums, ", counts do not match")

        
